language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - node
services:
  - docker
env:
  global:
    - PGPORT=7777
  matrix:
    - PACKAGE=skitch-testing
    - PACKAGE=skitch-transform
before_install:
  - yarn add global lerna
  - docker run -p 7777:5432 --name postgritty -d postgres:9.6
script:
  - lerna run test --scope $PACKAGE
