language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
services:
  - docker
env:
  - PGPORT=7777
before_install:
  - docker run -p 7777:5432 --name postgritty -d pyramation/postgres-plv8
  - sleep 3
  - while ! docker exec -it postgritty pg_isready -U postgres -h 127.0.0.1; do echo "$(date) - waiting for database to start"; sleep 1; done
script:
  - npm run test
